parser: "babel-eslint"

extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "airbnb-base"

env:
  node: true
  browser: true

plugins: ["react"]

rules:
  no-console: 0
  linebreak-style: 0
  react/prop-types: 0
  import/no-unresolved: 0
  import/extensions: 0
  no-tabs: 0
  indent: 0
